"""empty message

Revision ID: 09798c3c4664
Revises: 5a40533ea23a
Create Date: 2025-03-07 22:52:30.946413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09798c3c4664'
down_revision = '5a40533ea23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_expenses_user", 'users', ['user_id'], ['id'])  # ✅ Named FK Constraint

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_income_user", 'users', ['user_id'], ['id'])  # ✅ Named FK Constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint("fk_income_user", type_='foreignkey')  # ✅ Use correct constraint name

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint("fk_expenses_user", type_='foreignkey')  # ✅ Use correct constraint name

    # ### end Alembic commands ###
